-- =============================================================================
-- ⚠️  FILE INI SUDAH PINDAH
-- =============================================================================
-- Tabel arcade_song & arcade_score sekarang bagian dari migration gabungan.
--
-- Untuk membuat SEMUA tabel arcade (rooms, moves, arcade_song, arcade_score):
--   php arcade/migrate.php
--
-- Atau import manual:
--   mysql -u root -p MEeL < arcade/schema.sql
--
-- File arcade/schema.sql berisi:
--   - rooms       (chess multiplayer)
--   - moves       (chess move history)
--   - arcade_song (MEeL!Mania song metadata)
--   - arcade_score(MEeL!Mania scores)
-- =============================================================================
